<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Nitro5Omar" failures="1" tests="5" name="Personal Loan" time="0.041" errors="0" timestamp="19 May 2025 20:15:28 GMT">
  <testcase classname="test.Day1" name="demo" time="0.012">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at test.Day1.demo(Day1.java:17)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- demo -->
  <testcase classname="test.Day2" name="ploan" time="0.003"/>
  <testcase classname="test.Day4" name="LoginAPIHomeLoan" time="0.001"/>
  <testcase classname="test.Day4" name="MobileLoginHomeLoan" time="0.001"/>
  <testcase classname="test.Day4" name="WebloginHomeLoan" time="0.003"/>
</testsuite> <!-- Personal Loan -->
